--- 
institution: 
  name: TSL
  logo: images/TSL.png
  url: http://www.tsl.ac.uk
service: 
  format: Unspecified
  title: GeeFu
  server: Unspecified
  version: Vers 1
  access: public
  description: GeeFu
engineer: 
  name: Martin Page
  email: martin.page@tsl.ac.uk
genome: 
  version: KW1
  description: Chalara
  species: Chalara Fraxinea